### ISSUE TITLE
ant, testablemock, junit, jacoco,不能生成覆盖率报告

### ISSUE THREAD

**Issue by Xiangqian-Dong** [alibaba/testable-mock#178]
我的项目用的ant的xml编译，跑测试用例，测试用例使用了testablemock。测试用例可以编译，跑过。ant的覆盖率
文件jacoco.exec也生成了。但是在生成覆盖率报告的时候，错误，大概意思是：覆盖率文件和class文件不匹配。都是使用java8.
如果不使用testablemock，覆盖率报告就没问题。
testablemock文档中说使用argline，可那是maven的，ant中没有这个。这个要怎么解决，谢谢了？

**Comment by Vickcle** [comment]
实际上，我的项目上也遇到了同样的问题，Maven的项目，加了argline,测试用例会全部跳过。因为这个原因也无法生成测试报告。

**Comment by linfan** [comment]
@Vickcle 如果是使用JUnit 5的话，需要 maven-surefire-plugin 3.0.0+ 版本

**Comment by Vickcle** [comment]
感谢回复，问题已解决。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Fan ***@***.***&gt;; 
发送时间: 2021年8月11日(星期三) 下午4:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/testable-mock] ant, testablemock, junit, jacoco,不能生成覆盖率报告 (#178)





 
@Vickcle 如果是使用JUnit 5的话，需要 maven-surefire-plugin 3.0.0+ 版本
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
